use icicle_vm::cpu::mem::MemResult;
#[derive(Default)]
#[doc = "SWI0: Software interrupt 0<br>EGU0: Event Generator Unit 0<br><br>Instances:<br>0x40014000: SWI0, EGU0<br>0x40015000: SWI1, EGU1<br>0x40016000: SWI2, EGU2<br>0x40017000: SWI3, EGU3<br>0x40018000: SWI4, EGU4<br>0x40019000: SWI5, EGU5<br>"]
pub struct Apb20 {
    #[doc = "TODO: implement things here"]
    _todo: (),
}
impl Apb20 {
    pub(crate) fn page_to_index(page: u64) -> usize {
        match page {
            262164u64 => 0usize,
            262165u64 => 1usize,
            262166u64 => 2usize,
            262167u64 => 3usize,
            262168u64 => 4usize,
            262169u64 => 5usize,
            _ => unreachable!(),
        }
    }
    #[doc = "TASKS_TRIGGER\\[%s\\]: Description collection\\[0\\]:  Trigger 0 for triggering the corresponding TRIGGERED\\[0\\] event<br>UNUSED: Unused.<br>"]
    pub(crate) fn apb20_tasks_triggern0_write(
        &mut self,
        _reg_array: usize,
        _value: u32,
    ) -> MemResult<()> {
        todo ! ("write apb20_tasks_triggern0 mwrite None write None rac None reset value 0x00 mask 0x00")
    }
    #[doc = "EVENTS_TRIGGERED\\[%s\\]: Description collection\\[0\\]:  Event number 0 generated by triggering the corresponding TRIGGER\\[0\\] task<br>"]
    pub(crate) fn apb20_events_triggeredn100_read(
        &self,
        _reg_array: usize,
    ) -> MemResult<u32> {
        todo ! ("read apb20_events_triggeredn100 mwrite None write None rac None reset value 0x00 mask 0x00")
    }
    #[doc = "EVENTS_TRIGGERED\\[%s\\]: Description collection\\[0\\]:  Event number 0 generated by triggering the corresponding TRIGGER\\[0\\] task<br>"]
    pub(crate) fn apb20_events_triggeredn100_write(
        &mut self,
        _reg_array: usize,
        _value: u32,
    ) -> MemResult<()> {
        todo ! ("write apb20_events_triggeredn100 mwrite None write None rac None reset value 0x00 mask 0x00")
    }
    #[doc = "TRIGGERED0: Enable or disable interrupt for TRIGGERED\\[0\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered0_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED0 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED0: Enable or disable interrupt for TRIGGERED\\[0\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered0_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED0 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED1: Enable or disable interrupt for TRIGGERED\\[1\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered1_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED1 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED1: Enable or disable interrupt for TRIGGERED\\[1\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered1_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED1 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED2: Enable or disable interrupt for TRIGGERED\\[2\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered2_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED2 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED2: Enable or disable interrupt for TRIGGERED\\[2\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered2_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED2 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED3: Enable or disable interrupt for TRIGGERED\\[3\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered3_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED3 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED3: Enable or disable interrupt for TRIGGERED\\[3\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered3_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED3 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED4: Enable or disable interrupt for TRIGGERED\\[4\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered4_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED4 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED4: Enable or disable interrupt for TRIGGERED\\[4\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered4_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED4 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED5: Enable or disable interrupt for TRIGGERED\\[5\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered5_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED5 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED5: Enable or disable interrupt for TRIGGERED\\[5\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered5_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED5 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED6: Enable or disable interrupt for TRIGGERED\\[6\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered6_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED6 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED6: Enable or disable interrupt for TRIGGERED\\[6\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered6_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED6 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED7: Enable or disable interrupt for TRIGGERED\\[7\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered7_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED7 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED7: Enable or disable interrupt for TRIGGERED\\[7\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered7_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED7 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED8: Enable or disable interrupt for TRIGGERED\\[8\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered8_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED8 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED8: Enable or disable interrupt for TRIGGERED\\[8\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered8_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED8 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED9: Enable or disable interrupt for TRIGGERED\\[9\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered9_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED9 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED9: Enable or disable interrupt for TRIGGERED\\[9\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered9_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED9 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED10: Enable or disable interrupt for TRIGGERED\\[10\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered10_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED10 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED10: Enable or disable interrupt for TRIGGERED\\[10\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered10_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED10 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED11: Enable or disable interrupt for TRIGGERED\\[11\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered11_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED11 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED11: Enable or disable interrupt for TRIGGERED\\[11\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered11_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED11 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED12: Enable or disable interrupt for TRIGGERED\\[12\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered12_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED12 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED12: Enable or disable interrupt for TRIGGERED\\[12\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered12_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED12 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED13: Enable or disable interrupt for TRIGGERED\\[13\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered13_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED13 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED13: Enable or disable interrupt for TRIGGERED\\[13\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered13_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED13 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED14: Enable or disable interrupt for TRIGGERED\\[14\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered14_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED14 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED14: Enable or disable interrupt for TRIGGERED\\[14\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered14_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED14 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED15: Enable or disable interrupt for TRIGGERED\\[15\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered15_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED15 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED15: Enable or disable interrupt for TRIGGERED\\[15\\] event<br>"]
    pub(crate) fn apb20_inten300_triggered15_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED15 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED0: Write '1' to Enable interrupt for TRIGGERED\\[0\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered0_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED0 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED0: Write '1' to Enable interrupt for TRIGGERED\\[0\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered0_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED0 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED1: Write '1' to Enable interrupt for TRIGGERED\\[1\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered1_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED1 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED1: Write '1' to Enable interrupt for TRIGGERED\\[1\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered1_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED1 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED2: Write '1' to Enable interrupt for TRIGGERED\\[2\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered2_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED2 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED2: Write '1' to Enable interrupt for TRIGGERED\\[2\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered2_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED2 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED3: Write '1' to Enable interrupt for TRIGGERED\\[3\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered3_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED3 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED3: Write '1' to Enable interrupt for TRIGGERED\\[3\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered3_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED3 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED4: Write '1' to Enable interrupt for TRIGGERED\\[4\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered4_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED4 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED4: Write '1' to Enable interrupt for TRIGGERED\\[4\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered4_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED4 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED5: Write '1' to Enable interrupt for TRIGGERED\\[5\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered5_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED5 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED5: Write '1' to Enable interrupt for TRIGGERED\\[5\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered5_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED5 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED6: Write '1' to Enable interrupt for TRIGGERED\\[6\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered6_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED6 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED6: Write '1' to Enable interrupt for TRIGGERED\\[6\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered6_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED6 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED7: Write '1' to Enable interrupt for TRIGGERED\\[7\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered7_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED7 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED7: Write '1' to Enable interrupt for TRIGGERED\\[7\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered7_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED7 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED8: Write '1' to Enable interrupt for TRIGGERED\\[8\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered8_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED8 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED8: Write '1' to Enable interrupt for TRIGGERED\\[8\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered8_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED8 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED9: Write '1' to Enable interrupt for TRIGGERED\\[9\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered9_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED9 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED9: Write '1' to Enable interrupt for TRIGGERED\\[9\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered9_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED9 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED10: Write '1' to Enable interrupt for TRIGGERED\\[10\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered10_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED10 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED10: Write '1' to Enable interrupt for TRIGGERED\\[10\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered10_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED10 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED11: Write '1' to Enable interrupt for TRIGGERED\\[11\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered11_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED11 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED11: Write '1' to Enable interrupt for TRIGGERED\\[11\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered11_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED11 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED12: Write '1' to Enable interrupt for TRIGGERED\\[12\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered12_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED12 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED12: Write '1' to Enable interrupt for TRIGGERED\\[12\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered12_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED12 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED13: Write '1' to Enable interrupt for TRIGGERED\\[13\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered13_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED13 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED13: Write '1' to Enable interrupt for TRIGGERED\\[13\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered13_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED13 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED14: Write '1' to Enable interrupt for TRIGGERED\\[14\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered14_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED14 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED14: Write '1' to Enable interrupt for TRIGGERED\\[14\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered14_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED14 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED15: Write '1' to Enable interrupt for TRIGGERED\\[15\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered15_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED15 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED15: Write '1' to Enable interrupt for TRIGGERED\\[15\\] event<br>"]
    pub(crate) fn apb20_intenset304_triggered15_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED15 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED0: Write '1' to Disable interrupt for TRIGGERED\\[0\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered0_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED0 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED0: Write '1' to Disable interrupt for TRIGGERED\\[0\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered0_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED0 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED1: Write '1' to Disable interrupt for TRIGGERED\\[1\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered1_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED1 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED1: Write '1' to Disable interrupt for TRIGGERED\\[1\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered1_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED1 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED2: Write '1' to Disable interrupt for TRIGGERED\\[2\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered2_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED2 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED2: Write '1' to Disable interrupt for TRIGGERED\\[2\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered2_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED2 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED3: Write '1' to Disable interrupt for TRIGGERED\\[3\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered3_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED3 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED3: Write '1' to Disable interrupt for TRIGGERED\\[3\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered3_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED3 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED4: Write '1' to Disable interrupt for TRIGGERED\\[4\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered4_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED4 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED4: Write '1' to Disable interrupt for TRIGGERED\\[4\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered4_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED4 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED5: Write '1' to Disable interrupt for TRIGGERED\\[5\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered5_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED5 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED5: Write '1' to Disable interrupt for TRIGGERED\\[5\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered5_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED5 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED6: Write '1' to Disable interrupt for TRIGGERED\\[6\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered6_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED6 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED6: Write '1' to Disable interrupt for TRIGGERED\\[6\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered6_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED6 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED7: Write '1' to Disable interrupt for TRIGGERED\\[7\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered7_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED7 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED7: Write '1' to Disable interrupt for TRIGGERED\\[7\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered7_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED7 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED8: Write '1' to Disable interrupt for TRIGGERED\\[8\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered8_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED8 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED8: Write '1' to Disable interrupt for TRIGGERED\\[8\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered8_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED8 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED9: Write '1' to Disable interrupt for TRIGGERED\\[9\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered9_read(&self) -> MemResult<bool> {
        todo!(
            "read TRIGGERED9 mwrite None write None rac None reset value false"
        )
    }
    #[doc = "TRIGGERED9: Write '1' to Disable interrupt for TRIGGERED\\[9\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered9_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED9 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED10: Write '1' to Disable interrupt for TRIGGERED\\[10\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered10_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED10 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED10: Write '1' to Disable interrupt for TRIGGERED\\[10\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered10_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED10 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED11: Write '1' to Disable interrupt for TRIGGERED\\[11\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered11_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED11 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED11: Write '1' to Disable interrupt for TRIGGERED\\[11\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered11_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED11 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED12: Write '1' to Disable interrupt for TRIGGERED\\[12\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered12_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED12 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED12: Write '1' to Disable interrupt for TRIGGERED\\[12\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered12_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED12 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED13: Write '1' to Disable interrupt for TRIGGERED\\[13\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered13_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED13 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED13: Write '1' to Disable interrupt for TRIGGERED\\[13\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered13_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED13 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED14: Write '1' to Disable interrupt for TRIGGERED\\[14\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered14_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED14 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED14: Write '1' to Disable interrupt for TRIGGERED\\[14\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered14_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED14 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED15: Write '1' to Disable interrupt for TRIGGERED\\[15\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered15_read(&self) -> MemResult<bool> {
        todo ! ("read TRIGGERED15 mwrite None write None rac None reset value false")
    }
    #[doc = "TRIGGERED15: Write '1' to Disable interrupt for TRIGGERED\\[15\\] event<br>"]
    pub(crate) fn apb20_intenclr308_triggered15_write(
        &mut self,
        _value: bool,
    ) -> MemResult<()> {
        todo ! ("write TRIGGERED15 mwrite None write None rac None reset value false")
    }
}
